name: pyre

on: [push, pull_request]

jobs:
  pyre:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Expose SARIF Results
        uses: actions/upload-artifact@v2
        with:
          name: SARIF Results
          path: sarif.json

      - name: Upload SARIF Results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: sarif.json
